//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agoda.Analyzers.AgodaCustom {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomRulesResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomRulesResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Agoda.Analyzers.AgodaCustom.CustomRulesResources", typeof(CustomRulesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AG0001Description {
            get {
                return ResourceManager.GetString("AG0001Description", resourceCulture);
            }
        }
        
        public static string AG0001MessageFormat {
            get {
                return ResourceManager.GetString("AG0001MessageFormat", resourceCulture);
            }
        }
        
        public static string AG0001Title {
            get {
                return ResourceManager.GetString("AG0001Title", resourceCulture);
            }
        }
        
        public static string AG0002Description {
            get {
                return ResourceManager.GetString("AG0002Description", resourceCulture);
            }
        }
        
        public static string AG0002MessageFormat {
            get {
                return ResourceManager.GetString("AG0002MessageFormat", resourceCulture);
            }
        }
        
        public static string AG0002Title {
            get {
                return ResourceManager.GetString("AG0002Title", resourceCulture);
            }
        }
        
        public static string AG0003Description {
            get {
                return ResourceManager.GetString("AG0003Description", resourceCulture);
            }
        }
        
        public static string AG0003MessageFormat {
            get {
                return ResourceManager.GetString("AG0003MessageFormat", resourceCulture);
            }
        }
        
        public static string AG0003Title {
            get {
                return ResourceManager.GetString("AG0003Title", resourceCulture);
            }
        }
        
        public static string AG0004Title {
            get {
                return ResourceManager.GetString("AG0004Title", resourceCulture);
            }
        }
        
        public static string AG0005Title {
            get {
                return ResourceManager.GetString("AG0005Title", resourceCulture);
            }
        }
        
        public static string AG0006Title {
            get {
                return ResourceManager.GetString("AG0006Title", resourceCulture);
            }
        }
        
        public static string AG0020FixTitle {
            get {
                return ResourceManager.GetString("AG0020FixTitle", resourceCulture);
            }
        }
        
        public static string AG0020Title {
            get {
                return ResourceManager.GetString("AG0020Title", resourceCulture);
            }
        }
        
        public static string AG0011Title {
            get {
                return ResourceManager.GetString("AG0011Title", resourceCulture);
            }
        }
        
        public static string AG0009Title {
            get {
                return ResourceManager.GetString("AG0009Title", resourceCulture);
            }
        }
        
        public static string AG0009Description {
            get {
                return ResourceManager.GetString("AG0009Description", resourceCulture);
            }
        }
        
        public static string AG0009MessageFormat {
            get {
                return ResourceManager.GetString("AG0009MessageFormat", resourceCulture);
            }
        }
        
        public static string AG0012Title {
            get {
                return ResourceManager.GetString("AG0012Title", resourceCulture);
            }
        }
        
        public static string AG0013Title {
            get {
                return ResourceManager.GetString("AG0013Title", resourceCulture);
            }
        }
        
        public static string AG0022Description {
            get {
                return ResourceManager.GetString("AG0022Description", resourceCulture);
            }
        }
        
        public static string AG0022MessageFormat {
            get {
                return ResourceManager.GetString("AG0022MessageFormat", resourceCulture);
            }
        }
        
        public static string AG0022Title {
            get {
                return ResourceManager.GetString("AG0022Title", resourceCulture);
            }
        }
        
        public static string AG0021Title {
            get {
                return ResourceManager.GetString("AG0021Title", resourceCulture);
            }
        }
        
        public static string AG0025Title {
            get {
                return ResourceManager.GetString("AG0025Title", resourceCulture);
            }
        }
        
        public static string AG0030Title {
            get {
                return ResourceManager.GetString("AG0030Title", resourceCulture);
            }
        }
        
        public static string AG0018Title {
            get {
                return ResourceManager.GetString("AG0018Title", resourceCulture);
            }
        }
        
        public static string AG0026Title {
            get {
                return ResourceManager.GetString("AG0026Title", resourceCulture);
            }
        }
        
        public static string AG0010Title {
            get {
                return ResourceManager.GetString("AG0010Title", resourceCulture);
            }
        }
        
        public static string AG0022FixTitle {
            get {
                return ResourceManager.GetString("AG0022FixTitle", resourceCulture);
            }
        }
        
        public static string AG0019Title {
            get {
                return ResourceManager.GetString("AG0019Title", resourceCulture);
            }
        }
        
        public static string AG0019FixTitle {
            get {
                return ResourceManager.GetString("AG0019FixTitle", resourceCulture);
            }
        }
        
        public static string AG0023Title {
            get {
                return ResourceManager.GetString("AG0023Title", resourceCulture);
            }
        }
        
        public static string AG0027Title {
            get {
                return ResourceManager.GetString("AG0027Title", resourceCulture);
            }
        }
        
        public static string AG0024Title {
            get {
                return ResourceManager.GetString("AG0024Title", resourceCulture);
            }
        }
        
        public static string AG0032Title {
            get {
                return ResourceManager.GetString("AG0032Title", resourceCulture);
            }
        }
        
        public static string AG0033Title {
            get {
                return ResourceManager.GetString("AG0033Title", resourceCulture);
            }
        }
        
        public static string AG0035Description {
            get {
                return ResourceManager.GetString("AG0035Description", resourceCulture);
            }
        }
        
        public static string AG0035Title {
            get {
                return ResourceManager.GetString("AG0035Title", resourceCulture);
            }
        }
        
        public static string AG0037Description {
            get {
                return ResourceManager.GetString("AG0037Description", resourceCulture);
            }
        }
        
        public static string AG0037Title {
            get {
                return ResourceManager.GetString("AG0037Title", resourceCulture);
            }
        }
        
        public static string AG0038Title {
            get {
                return ResourceManager.GetString("AG0038Title", resourceCulture);
            }
        }
        
        public static string AG0039Title {
            get {
                return ResourceManager.GetString("AG0039Title", resourceCulture);
            }
        }
        
        public static string AG0040Title {
            get {
                return ResourceManager.GetString("AG0040Title", resourceCulture);
            }
        }
        
        public static string AG0040MessageFormat {
            get {
                return ResourceManager.GetString("AG0040MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using either an interpolated string or concatenation string in your logs, change these to the message template format to preserve structure in your logs.
        /// </summary>
        public static string AG0041Title {
            get {
                return ResourceManager.GetString("AG0041Title", resourceCulture);
            }
        }
        
        public static string AG0042Title {
            get {
                return ResourceManager.GetString("AG0042Title", resourceCulture);
            }
        }
    }
}
